title: Eiman Siddiqui

exclude: [screenshots, LICENSE, README.md]
markdown: kramdown

buttons:
 - text: Home
   url: /
 - text: Work
   url: work
 - text: Projects
   url: projects

social:
  - type: email
    value: mailto:eimansiddiqui@gmail.com
    class: envelope-o
  - type: github
    value: https://github.com/eCDKEY
    class: github
  - type: linkedin
    value: https://linkedin.com/in/eimansiddiqui
    class: linkedin
  - type: twitter
    value: https://twitter.com/eimansiddiqui
    class: twitter
