title: Eiman Siddiqui

email: eimansiddiqui@gmail.com
github_url: https://github.com/eCDKEY
linkedin_url: https://linkedin.com/in/eimansiddiqui
twitter_url: https://twitter.com/eimansiddiqui

exclude: [screenshots, LICENSE, README.md]
markdown: kramdown

button_1_text: Home
button_1_url: index

button_2_text: Work
button_2_url: work

button_3_text: Home
button_3_url: index
